eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

server:
  port: 8761

spring:
  application:
    name: eureka-server