hibernate:
  jdbc:
    time_zone: UTC
  show_sql: true

ru:
  yandex:
    practicum:
      payment:
        deliveryCost: 50
        valueAddedTax: 10

server:
  port: 0

spring:
  application:
    name: payment
  dataSource:
    driverClassName: org.postgresql.Driver
    password: 1qaz!QAZ
    url: jdbc:postgresql://localhost:6544/payment
    username: dbuser
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always