collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "telemetry.collector"
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        hubs-events: telemetry.hubs.v1
        sensors-events: telemetry.sensors.v1

spring:
  application:
    name: collector