hibernate:
  jdbc:
    time_zone: UTC
  show_sql: true

server:
  port: 0

spring:
  application:
    name: shopping-store
  dataSource:
    driverClassName: org.postgresql.Driver
    password: 1qaz!QAZ
    url: jdbc:postgresql://localhost:6546/shopping-store
    username: dbuser
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always